; The editor is a fullscreen aioli app: all in one lisp.
; Layout, paint, controls, and interactions all live here.
(init! :ui-bg "#101613")
(init! :ui-panel "#171e19")
(init! :ui-text "#d0dbd2")
(init! :ui-muted "#77867b")
(init! :ui-accent "#bbd6a6")
(init! :tab "scene")
(init! :show-code true)
(init! :show-tools false)
(init! :tool "graphics")
(init! :menu false)
(init! :paused false)
(init! :window "")
(init! :file-offset 0)
(init! :selected-file "scene.lisp")

(defn editor []
  (let [w (screen-width) h (screen-height)
        narrow (< w 850)
        code-width (if (get :show-code)
                       (if narrow w (floor (* w 0.42))) 0)
        tools-width (if (and (get :show-tools) (not narrow)) 264 0)
        world-x code-width
        world-width (- w code-width tools-width)]
    (background (get :ui-bg))
    (fill (get :ui-text))
    (when (> w 600) (text [24 18] "aioli"))

    ; A single quiet toolbar. Tools stay tucked away.
    (when (ui-button :project "Project" [(if narrow 16 140) 10] [80 32] (get :menu))
      (set! :menu (not (get :menu))))
    (when (> w 650)
      (when (ui-button :files "Files" [232 10] [68 32] (= (get :window) "files"))
        (set! :window "files") (set! :menu false))
      (when (ui-button :commands "Commands" [308 10] [100 32] (= (get :window) "palette"))
        (set! :window "palette") (set! :menu false)))
    (when (ui-button :code "Code" [(- w 240) 10] [68 32] (get :show-code))
      (set! :show-code (not (get :show-code))))
    (when (ui-button :tools "Tools" [(- w 164) 10] [68 32] (get :show-tools))
      (set! :show-tools (not (get :show-tools))))
    (when (ui-button :evaluate "Run" [(- w 88) 10] [64 32] true)
      (evaluate-project))
    (when (and (recovery?) (> w 850))
      (when (ui-button :upgrade-editor "Use latest editor" [424 10] [156 32] false)
        (upgrade-editor)))
    (fill "#27312a") (rect [0 50] [w 1])

    (when (get :show-code)
      (fill (get :ui-panel))
      (rect [0 51] [code-width (- h 81)])
      (ui-tab "scene" "scene" 16 (get :tab))
      (ui-tab "game" "game" 90 (get :tab))
      (ui-tab "audio" "audio" 164 (get :tab))
      (ui-tab "editor" "editor" 238 (get :tab))
      (when (> code-width 385)
        (ui-tab "ui" "ui" 312 (get :tab)))
      (if (= (get :window) "")
        (code-editor [16 110] [(- code-width 32) (- h 158)] (get :tab))
        (do (fill (get :ui-muted)) (text [24 114] "Tool window active")))
      (when (not (or (= (get :tab) "scene") (= (get :tab) "game")
                     (= (get :tab) "audio") (= (get :tab) "editor") (= (get :tab) "ui")))
        (fill (get :ui-muted)) (text [24 94] (get :tab))))

    (when (or (not narrow) (not (get :show-code)))
      (let [scale (max 0.3 (min 3 (floor
                    (min (/ (- world-width 64) 320) (/ (- h 190) 240)))))
            sw (* 320 scale) sh (* 240 scale)
            sx (+ world-x (/ (- world-width sw) 2))
            sy (+ 88 (/ (- (- h 170) sh) 2))]
        (fill (get :ui-muted))
        (text [sx (- sy 30)] "Midnight garden")
        (surface [sx sy] [sw sh])
        (fill (get :ui-muted))
        (text [sx (+ sy sh 18)] "A/D to move  /  Space to jump")
        (when (ui-button :pause (if (get :paused) "Play" "Pause")
                         [(+ sx sw -70) (- sy 38)] [70 32] false)
          (set! :paused (not (get :paused))))))

    (when (get :show-tools)
      (let [x (if narrow (- w 264) (- w tools-width)) y 76]
        (fill (get :ui-panel))
        (rect [x 51] [264 (- h 81)])
        (when (ui-button :graphics "Graphics" [(+ x 16) y] [108 32]
                         (= (get :tool) "graphics")) (set! :tool "graphics"))
        (when (ui-button :sound "Sound" [(+ x 132) y] [108 32]
                         (= (get :tool) "sound")) (set! :tool "sound"))
        (scope
          (clip [(+ x 16) 126] [232 (- h 160)])
          (if (= (get :tool) "graphics")
              (graphics-tools (+ x 16) 136 232)
              (sound-tools (+ x 16) 136 232)))))

    ; File actions and references are only visible on demand.
    (when (get :menu)
      (fill "#27312a") (rect [140 48] [192 (if (recovery?) 582 502)])
      (fill (get :ui-panel)) (rect [141 49] [190 (if (recovery?) 580 500)])
      (when (ui-button :export "Save project" [150 60] [172 32] false)
        (export-project) (set! :menu false))
      (when (ui-button :import "Open project" [150 100] [172 32] false)
        (import-project) (set! :menu false))
      (when (ui-button :png "Save image" [150 140] [172 32] false)
        (export-png) (set! :menu false))
      (when (ui-button :preset "Next scene" [150 180] [172 32] false)
        (next-scene) (set! :menu false))
      (when (ui-button :reset "Reset state" [150 220] [172 32] false)
        (reset-project) (set! :menu false))
      (when (ui-button :wgsl "View WGSL" [150 260] [172 32] false)
        (set! :tab "wgsl") (set! :show-code true) (set! :menu false))
      (when (ui-button :help "Language guide" [150 300] [172 32] false)
        (set! :tab "guide") (set! :show-code true) (set! :menu false))
      (when (ui-button :docs "Documentation" [150 340] [172 32] false)
        (open-docs) (set! :menu false))
      (when (ui-button :image-generator "Image generator" [150 380] [172 32] false)
        (set! :window "image") (set! :menu false))
      (when (ui-button :audio-generator "Audio generator" [150 420] [172 32] false)
        (set! :window "audio") (set! :menu false))
      (when (ui-button :project-files "File explorer" [150 460] [172 32] false)
        (set! :window "files") (set! :menu false))
      (when (ui-button :command-palette "Command palette" [150 500] [172 32] false)
        (set! :window "palette") (set! :menu false))
      (when (recovery?)
        (when (ui-button :adopt-editor "Use latest editor" [150 540] [172 32] false)
          (upgrade-editor) (set! :menu false))
        (when (ui-button :leave-recovery "Project editor" [150 580] [172 32] false)
          (leave-recovery) (set! :menu false))))

    ; Overlay widgets paint last, giving their regions pointer priority.
    (when (not (= (get :window) "")) (project-window))

    (fill (get :ui-bg)) (rect [0 (- h 30)] [w 30])
    (fill (if (error?) "#e8ac94" (get :ui-muted)))
    (scope (clip [24 (- h 24)] [(- w 240) 20])
      (text [24 (- h 22)] (status)))
    (when (error?)
      (region :diagnostic "View error details" [0 (- h 30)] [(- w 210) 30])
      (when (or (activated? :diagnostic)
                (and (pointer-pressed?) (hit? [0 (- h 30)] [(- w 210) 30])))
        (set! :tab "diagnostic") (set! :show-code true)))
    (fill (get :ui-muted))
    (text [(- w 186) (- h 22)] "Ctrl+Enter to run")))
