import { templatePaths, policyPaths } from './editor-policy.js';
/** Bundled Lisp modules. Paths are project data, so imports stay local and live. */
export const editorSourcePaths = [
  ...templatePaths,
  'editor/guide.txt',
  'editor/theme.lisp',
  ...policyPaths,
  'editor/ui/components.lisp',
  'editor/ui/layout.lisp',
  'editor/ui/docking.lisp',
  'editor/ui/code-input.lisp',
  'editor/ui/buttons.lisp',
  'editor/ui/sliders.lisp',
  'editor/ui/asset-icon.lisp',
  'editor/ui/menu.lisp',
  'editor/tool-window.lisp',
  'editor/files-pane.lisp',
  'editor/filename-dialog.lisp',
  'editor/file-context-menu.lisp',
  'editor/command-palette.lisp',
  'editor/generator-window.lisp',
  'editor/menu-bar.lisp',
  'editor/about.lisp',
  'editor/project-settings.lisp',
  'editor/ui/tabs.lisp',
  'editor/state.lisp',
  'editor/code-pane.lisp',
  'editor/game-pane.lisp',
  'editor/parameter-pane.lisp',
  'editor/workspace.lisp',
  'editor/docked-workspace.lisp',
  'editor/asset-preview.lisp',
];
