; Components own positioning, painting and input; this file describes the tool.
(defn project-settings-content [origin size]
  (ui/render origin size
    (ui/scroll :settings-scroll-area :settings-scroll (map :padding 16 :gap 12)
      [(ui/label "Name")
       (ui/input :project-name "Project name" :__projectName)
       (ui/label "Canvas / pixels")
       ((if (< (nth size 0) 320) ui/column ui/row) (map :gap 12)
         [(ui/column (map :grow 1 :gap 6)
            [(ui/muted "Width") (ui/input :canvas-width "Canvas width" :__canvasWidth)])
          (ui/column (map :grow 1 :gap 6)
            [(ui/muted "Height") (ui/input :canvas-height "Canvas height" :__canvasHeight)])])
       ((if (< (nth size 0) 400) ui/column ui/row) (map :gap 8)
         [(ui/button :canvas-retro "320x240" (fn [] (project-canvas-preset 320 240)))
          (ui/button :canvas-wide "640x360" (fn [] (project-canvas-preset 640 360)))
          (ui/button :canvas-square "512x512" (fn [] (project-canvas-preset 512 512)))])
       (ui/muted "16 to 2048 / whole pixels")
       (ui/muted (get :project-settings-error))
       (ui/row (map :gap 8)
         [(ui/button :canvas-apply "Apply" (fn [] (apply-project-settings)))
          (ui/button :settings-cancel "Cancel" (fn [] (set! :show-project-settings false) (set! :input-tab "")))])])))
