; The editor is a fullscreen aioli app: all in one lisp.
; Shared theme and workspace defaults, preserved through live reload.
(init! :ui-bg "#101613")
(init! :ui-panel "#171e19")
(init! :ui-text "#d0dbd2")
(init! :ui-muted "#77867b")
(init! :ui-accent "#bbd6a6")
(init! :tab "main")
(init! :show-code true)
(init! :show-tools false)
(init! :tool "graphics")
(init! :file-context false)
(init! :context-x 8)
(init! :context-y 90)
(init! :context-kind "")
(init! :context-path "")
(init! :file-operation "create")
(init! :menu false)
(when (= (get :menu) true) (set! :menu false))
(init! :paused false)
(init! :window "")
(init! :file-offset 0)
(init! :selected-file "main.lisp")
(init! :show-files false)
(init! :file-path-editing false)
(init! :open-folders "[]")
; Upgrade a saved modal explorer into the docked pane.
(when (= (get :window) "files") (set! :show-files true) (set! :window ""))


; Pan is in screen pixels; zoom multiplies the fitted image size.
(init! :preview-path "")
(init! :preview-zoom 1)
(init! :preview-pan-x 0)
(init! :preview-pan-y 0)
(init! :preview-drag-x 0)
(init! :preview-drag-y 0)
(init! :preview-drag-pan-x 0)
(init! :preview-drag-pan-y 0)
