; GHOST ORBITS — analytic raytracing, written entirely in ordinary pixel Lisp.
; Play this scene, click Game, and press F4 for the full view.
; A/D or Left/Right: orbit. W/S or Up/Down: zoom. Space: freeze the orbits.
; R: reset the camera. Inspector exposes camera, light and reflection settings.
; Primary rays intersect three spheres and a plane. The plane launches a second
; ray into the scene for real reflections; light rays give the floor soft shadows.

(init! :orbit-angle 0.35 ["Camera orbit" -3.14 3.14 0.01])
(init! :orbit-distance 6.5 ["Camera distance" 3.8 10 0.1])
(init! :orbit-height 2.7 ["Camera height" 1.2 5 0.1])
(init! :orbit-light 1.1 ["Light intensity" 0.2 2 0.05])
(init! :orbit-reflection 0.72 ["Floor reflection" 0 1 0.01])
(init! :orbit-clock 0)
(init! :orbit-frozen false ["Freeze orbits"])
(init! :orbit-space-held false)

(defn update [dt]
  (when (or (key? "a") (key? "ArrowLeft"))
    (set! :orbit-angle (- (get :orbit-angle) (* dt 0.9))))
  (when (or (key? "d") (key? "ArrowRight"))
    (set! :orbit-angle (+ (get :orbit-angle) (* dt 0.9))))
  (when (or (key? "w") (key? "ArrowUp"))
    (set! :orbit-distance (max 3.8 (- (get :orbit-distance) (* dt 2)))))
  (when (or (key? "s") (key? "ArrowDown"))
    (set! :orbit-distance (min 10 (+ (get :orbit-distance) (* dt 2)))))
  (when (and (key? " ") (not (get :orbit-space-held)))
    (set! :orbit-frozen (not (get :orbit-frozen))))
  (set! :orbit-space-held (key? " "))
  (when (not (get :orbit-frozen))
    (set! :orbit-clock (+ (get :orbit-clock) dt)))
  (when (key? "r")
    (set! :orbit-angle 0.35) (set! :orbit-distance 6.5) (set! :orbit-height 2.7)))

(defdraw render []
  (pixels [p time]
    (let [t (get :orbit-clock) yaw (get :orbit-angle)
          eye [(* (sin yaw) (get :orbit-distance)) (get :orbit-height)
               (* (cos yaw) (get :orbit-distance))]
          forward (normalize (- [0 0.9 0] eye))
          right [(cos yaw) 0 (- (sin yaw))]
          up (cross right forward)
          uv [(/ (- (* 2 p.x) width) height) (/ (- height (* 2 p.y)) height)]
          ray (normalize (+ (* forward 1.8) (* right uv.x) (* up uv.y)))
          c1 [(- 1.15) (+ 0.95 (* 0.18 (sin t))) (* 0.4 (cos (* t 0.7)))]
          c2 [1.05 (+ 0.7 (* 0.12 (sin (+ t 2)))) (- 0.6)]
          c3 [(* 1.4 (sin (* t 0.55))) (+ 1.75 (* 0.4 (cos (* t 0.8))))
              (* 1.2 (cos (* t 0.55)))]
          o1 (- eye c1) b1 (dot o1 ray) d1 (- (* b1 b1) (- (dot o1 o1) 0.64))
          h1 (- (- b1) (sqrt (max 0 d1)))
          s1 (mix 1000 h1 (* (step 0 d1) (step 0.02 h1)))
          o2 (- eye c2) b2 (dot o2 ray) d2 (- (* b2 b2) (- (dot o2 o2) 0.4225))
          h2 (- (- b2) (sqrt (max 0 d2)))
          s2 (mix 1000 h2 (* (step 0 d2) (step 0.02 h2)))
          o3 (- eye c3) b3 (dot o3 ray) d3 (- (* b3 b3) (- (dot o3 o3) 0.2025))
          h3 (- (- b3) (sqrt (max 0 d3)))
          s3 (mix 1000 h3 (* (step 0 d3) (step 0.02 h3)))
          floor-t (mix 1000 (/ (- eye.y) (min -0.0001 ray.y)) (step 0.0001 (- ray.y)))
          hit-t (min floor-t (min s1 (min s2 s3)))
          hit (- 1 (step 999 hit-t))
          floor-hit (* hit (step floor-t (min s1 (min s2 s3))))
          point (+ eye (* ray (min hit-t 100)))
          pick2 (step s2 s1) pick3 (step s3 (min s1 s2))
          center (mix (mix c1 c2 pick2) c3 pick3)
          albedo (mix (mix [0.62 0.82 0.75] [0.9 0.65 0.72] pick2) [0.7 0.61 0.85] pick3)
          normal (normalize (- point center))
          face (step 0.25 normal.z)
          eyes (- 1 (step 0.085 (length [(- (abs normal.x) 0.22) (- normal.y 0.13)])))
          smile (* (- 1 (step 0.13 (abs normal.x)))
                   (- 1 (step 0.025 (abs (- (+ normal.y 0.15) (* 0.4 normal.x normal.x))))))
          cheeks (- 1 (step 0.1 (length [(- (abs normal.x) 0.38) (+ normal.y 0.04)])))
          painted (mix (mix albedo [0.92 0.55 0.67] (* face cheeks))
                       [0.055 0.06 0.1] (* face (max eyes smile)))
          light (normalize [-3 5 2])
          diffuse (max 0 (dot normal light))
          specular (pow (max 0 (dot normal (normalize (- light ray)))) 64)
          rim (pow (- 1 (max 0 (dot normal (- ray)))) 3)
          sky (mix [0.025 0.035 0.09] [0.2 0.1 0.32] (pow (max 0 (- 1 (abs ray.y))) 4))
          sphere-color (+ (* painted (+ 0.16 (* (get :orbit-light) diffuse)))
                          (* [1 0.85 0.7] specular (get :orbit-light)) (* [0.3 0.6 1] rim 0.5))
          reflected (reflect ray [0 1 0])
          origin (+ point [0 0.015 0])
          r1 (- origin c1) rb1 (dot r1 reflected)
          rd1 (- (* rb1 rb1) (- (dot r1 r1) 0.64))
          rh1 (- (- rb1) (sqrt (max 0 rd1)))
          rt1 (mix 1000 rh1 (* (step 0 rd1) (step 0.02 rh1)))
          r2 (- origin c2) rb2 (dot r2 reflected)
          rd2 (- (* rb2 rb2) (- (dot r2 r2) 0.4225))
          rh2 (- (- rb2) (sqrt (max 0 rd2)))
          rt2 (mix 1000 rh2 (* (step 0 rd2) (step 0.02 rh2)))
          r3 (- origin c3) rb3 (dot r3 reflected)
          rd3 (- (* rb3 rb3) (- (dot r3 r3) 0.2025))
          rh3 (- (- rb3) (sqrt (max 0 rd3)))
          rt3 (mix 1000 rh3 (* (step 0 rd3) (step 0.02 rh3)))
          reflection-t (min rt1 (min rt2 rt3))
          reflection-hit (- 1 (step 999 reflection-t))
          rp2 (step rt2 rt1) rp3 (step rt3 (min rt1 rt2))
          reflection-center (mix (mix c1 c2 rp2) c3 rp3)
          reflection-albedo (mix (mix [0.62 0.82 0.75] [0.9 0.65 0.72] rp2) [0.7 0.61 0.85] rp3)
          reflection-normal (normalize (- (+ origin (* reflected (min reflection-t 100))) reflection-center))
          rface (step 0.25 reflection-normal.z)
          reyes (- 1 (step 0.085 (length [(- (abs reflection-normal.x) 0.22) (- reflection-normal.y 0.13)])))
          rsmile (* (- 1 (step 0.13 (abs reflection-normal.x)))
                    (- 1 (step 0.025 (abs (- (+ reflection-normal.y 0.15) (* 0.4 reflection-normal.x reflection-normal.x))))))
          rcheeks (- 1 (step 0.1 (length [(- (abs reflection-normal.x) 0.38) (+ reflection-normal.y 0.04)])))
          rpainted (mix (mix reflection-albedo [0.92 0.55 0.67] (* rface rcheeks))
                        [0.055 0.06 0.1] (* rface (max reyes rsmile)))
          reflection-color (* rpainted (+ 0.16 (* (get :orbit-light) (max 0 (dot reflection-normal light)))))
          checker (mod (+ (floor point.x) (floor point.z)) 2)
          grid (mix [0.045 0.065 0.1] [0.12 0.16 0.22] checker)
          ; Distance from the light ray to each sphere gives a smooth penumbra.
          l1 (- c1 origin) l2 (- c2 origin) l3 (- c3 origin)
          sh1 (mix 1 (smoothstep 0.72 0.9 (length (- l1 (* light (max 0 (dot l1 light)))))) (step 0 (dot l1 light)))
          sh2 (mix 1 (smoothstep 0.57 0.75 (length (- l2 (* light (max 0 (dot l2 light)))))) (step 0 (dot l2 light)))
          sh3 (mix 1 (smoothstep 0.39 0.54 (length (- l3 (* light (max 0 (dot l3 light)))))) (step 0 (dot l3 light)))
          shadow (* sh1 sh2 sh3)
          fresnel (+ 0.2 (* 0.8 (pow (- 1 (max 0 (- ray.y))) 5)))
          floor-color (mix (* grid (+ 0.25 (* 0.75 shadow)))
                          (mix sky reflection-color reflection-hit) (* (get :orbit-reflection) fresnel))
          scene-color (mix sky (mix sphere-color floor-color floor-hit) hit)
          fog (- 1 (pow 2.71828 (* -0.035 (min hit-t 100))))
          glow (* [0.1 0.2 0.35] (pow (max 0 (- 1 (abs ray.y))) 16))
          final (+ (mix scene-color sky (* hit fog)) glow)
          vignette (clamp (- 1 (* 0.14 (dot uv uv))) 0.35 1)]
      (background (* (pow (max final [0 0 0]) [0.8 0.8 0.8]) vignette))))
  (fill "#d5c5ed") (text [10 10] "GHOST ORBITS")
  (fill "#a6a69c")
  (text [10 (- (canvas-height) 28)] "A/D orbit  W/S zoom")
  (text [10 (- (canvas-height) 14)] (if (get :orbit-frozen) "Space resume  R reset" "Space freeze  R reset")))
