(let name "Ada")
(let draw (sh ()
  (let label (text
    (font "sans-serif")
    (size 32)
    (span "Hello ")
    (color (vec3 0.3 0.8 1))
    (span name)
    (line)
    (color (vec3 1))
    (span "This text is hoisted from the shader.")))
  (let uv (/ (- xy (vec2 24 24)) (vec2 label.w label.h)))
  (let pixel (sample label uv))
  (let inline (sample (text (size 20) (color (vec3 1 0.5 0.2)) (span "Inline text"))
    (/ (- xy (vec2 24 140)) (vec2 160 30))))
  (let background (vec3 0.04 0.05 0.08))
  (let first (blend pixel (vec4 background 1)))
  (return (blend inline first))))

(on render (context) (draw context))
